import type { Metadata } from 'next'
import { Fira_Code, Inter } from 'next/font/google'
import './globals.scss'
import CursorEffect from './components/CursorEffect/CursorEffect'

const fira = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nikulas Wraith',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fira.className}>
				<CursorEffect />
				{children}
				<div className="bg-grid"></div>
			</body>
    </html>
  )
}
